# Манифест для создания секретов
#  Версия API
apiVersion: v1
# Тип манифеста
kind: Secret
# Метаданные манифеста
metadata:
  # Имя манифеста
  name: {{ include "marmarks-chart.consumerSecrets.defaultName" . }}
  labels:
    # Метки манифеста
    {{- include "marmarks-chart.labels" . | nindent 4 }}
  # Тип секрета: неструктурированные данные. Храни просто пару "ключ-значение"
  # Без автоматического обновления, управления, ротации и т.д.
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "pgpass"
