apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marmarks-chart.consumerConfig.defaultName" . }}
  labels:
    {{- include "marmarks-chart.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: "dev"
  SERVER_PORT: "8080"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-dev:5432/postgres"

