apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "marmarks-chart.producerConfig.defaultName" . }}
  labels:
    {{- include "marmarks-chart.labels" . | nindent 4 }}
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-dev:5432/postgres"

